<a href="https://colab.research.google.com/github/BikramKC7/Fusemachines-Assessment/blob/main/data_wrangling_Bikram_KC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practice Data Wrangling

![](https://iili.io/3S2kRyu.png)

## Pandas


Pandas is a Python library extensively used for data analysis and manipulation. It provides data structures like DataFrames, which are similar to tables, and Series, which are like lists or columns in a table. These structures allow for efficient handling and processing of structured data. Pandas is built on top of NumPy and integrates well with other scientific computing libraries. It simplifies tasks such as data cleaning, transformation, and analysis, making it a fundamental tool for data scientists and analysts.

### Installing and Importing Pandas

Installing Pandas
```
pip install pandas
```

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

importing pandas

In [ ]:
## pd is widely used alias for pandas
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 50)

### Creating Series and Pandas Data Frame

#### 1. Creating Series
 A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It is similar to a column in a spreadsheet or a SQL table. The labels for the Series are collectively known as the index. A Series can be created from a variety of data types, including lists, dictionaries, and NumPy arrays.

In [ ]:
### Ex-1-Task-1

s = None
a = [1, 2, 3, 4, 5, 6]
# Task: create a series using list
### BEGIN SOLUTION
s = pd.Series(a)
print(s)
### END SOLUTION

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
### Ex-1-Task-2
a = {
    'a': 80,
    'b': 90,
    'c': 100
}
s = None
## Task: Create a series using dictionary
### BEGIN SOLUTION
s = pd.Series(a)
print(a)
### END SOLUTION

{'a': 80, 'b': 90, 'c': 100}

In [ ]:
### Ex-1-Task-3
a = [1, 2, 3, 4, 5, 6]
a = np.array(a)
s = None
## Creating a series using numpy array
### BEGIN SOLUTION
s = pd.Series(a)
print(s)
### END SOLUTION

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
### Ex-1-Task-4
population = {
    'Nepal': 30000000,
    'India': 1463865525,
    'Pakistan':255219554,
    'China': 1416096094
}
s = None
## Create a series with name 'population' and dtype='int64'
### BEGIN SOLUTION
s = pd.Series(population,name='population',dtype=np.int64)
print(s)
### END SOLUTION

Nepal         30000000
India       1463865525
Pakistan     255219554
China       1416096094
Name: population, dtype: int64

#### 2. Creating DataFrame

In [ ]:
### Ex-2-Task-1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
df = None
# Creating Data Frame from Python List
### BEGIN SOLUTION
df = pd.DataFrame(a,columns=['Numbers'])
print(df)
### END SOLUTION

   Numbers
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

In [ ]:
### Ex-2-Task-2
my_list = [['A', 1], ['B', 2], ['C', 3], ['D', 4]]
# Creating Data Frame from List of List
### BEGIN SOLUTION
df= pd.DataFrame(my_list,columns=['Letters','Numbers'])
print(df)
### END SOLUTION

  Letters  Numbers
0       A        1
1       B        2
2       C        3
3       D        4

In [ ]:
### Ex-2-Task-3
my_data = {
    'country': ['Nepal', 'India', 'China'],
    'Population': [30000000, 1463865525, 1416096094]
}
df = None
# Creating Data Frame using Python Dictionary
### BEGIN SOLUTION
df = pd.DataFrame(my_data)
print(df)
### END SOLUTION

  country  Population
0   Nepal    30000000
1   India  1463865525
2   China  1416096094

## Data Loading and Inspection

### Reading Data
A simple way to store big data is to use CSV files (comma Seperated files) or Parquet Files.
- df_sales --> computed_insight_success_of_active_sellers.csv'
- df_product --> summer-products-with-rating-and-performance_2020-08.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:


### Ex-3-Task-1
df_sales = None
df_product = None
# reading CSV file
### BEGIN SOLUTION
df_sales = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df_product = pd.read_csv('summer-products-with-rating-and-performance_2020-08.csv')
df_sales1 = df_sales.copy()
### END SOLUTION

### Basic Inspection

In [ ]:
### Ex-3-Task-2
head_df = None
tail_df = None
desribe_num_df = None
desribe_cate_df = None
# check the first 10 records of the sales dataframe
# check the last 10 records of the product dataframe
## Check the description of the numerical and categorical columns of prodcut dataframe
### BEGIN SOLUTION
head_df = df_sales.head(10)
tail_df = df_product.tail(10)
desribe_num_df = df_product.describe()
desribe_cate_df = df_product.describe(include='object')
tail_df
### END SOLUTION

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
1563,ZANZEA Femmes Été Polka Dot Kaftan Beach Club ...,ZANZEA Women Summer Polka Dot Kaftan Beach Clu...,15.00,92,EUR,100,0,3.51,74,26.0,15.0,15.0,7.0,11.0,0,0,0,0,"Summer,loosedresse,kaftan,long dress,baggydres...",red,L,50,Envio Padrão,4,0,38,50,NaN,NaN,CN,fashionforgirls,guangzhouchanny,"88% Feedback positivo (151,914 classificações)",151914,4.127921,53aa664438d3046ee44a5024,0,NaN,https://www.wish.com/c/5da04c1f5949a226113006f1,https://contestimg.wish.com/api/webimage/5da04...,5da04c1f5949a226113006f1,summer,2020-08
1564,2018 Femme mode d'été en dentelle Patchwork Pa...,2018 Women fashion Summer Lace Patchwork Tank ...,5.91,5,EUR,1000,0,3.38,414,156.0,58.0,72.0,45.0,83.0,0,0,0,0,"blouse,Summer,Vest,Fashion,Women Blouse,sleeve...",White,S,50,Livraison standard,2,0,36,50,1.0,Quantité limitée !,CN,liminny,liminny,"81 % avis positifs (12,134 notes)",12134,3.866903,58aec90823ef726994a323fe,0,NaN,https://www.wish.com/c/5b4ed29514f0765a8a844592,https://contestimg.wish.com/api/webimage/5b4ed...,5b4ed29514f0765a8a844592,summer,2020-08
1565,Nouveau Pantalon De Mode D'été Femmes Leggings...,New Summer Fashion Trousers Women Leggings Rip...,3.00,8,EUR,100,1,3.79,57,25.0,10.0,13.0,3.0,6.0,0,0,0,0,"Summer,Leggings,Fashion,high waist,pants,slim,...",skyblue,XS,1,Livraison standard,1,0,41,50,1.0,Quantité limitée !,CN,bujizhan,bujizhan,"(4,080 notes)",4080,3.987990,584a7a381591451e4e3af3df,0,NaN,https://www.wish.com/c/5e8f0165e815903d022a3c7c,https://contestimg.wish.com/api/webimage/5e8f0...,5e8f0165e815903d022a3c7c,summer,2020-08
1566,Robe mi-longue d'été à manches courtes pour fe...,Womens Short Sleeve Baggy Summer Beach Midi Dr...,11.00,134,EUR,100,1,3.54,28,7.0,11.0,4.0,2.0,4.0,0,0,0,0,"Summer,Shift Dress,Sleeve,shirt dress,long dre...",black,S,50,Livraison standard,3,0,46,50,NaN,NaN,CN,SCOMELY,scomely,"86 % avis positifs (1,926 notes)",1926,4.071651,593402ae25c4f54ed4e0abdf,0,NaN,https://www.wish.com/c/5d1060d39ed281190dfcec91,https://contestimg.wish.com/api/webimage/5d106...,5d1060d39ed281190dfcec91,summer,2020-08
1567,Combinaison sans manches pour femmes couleur u...,Sleeveless Solid Color Women Jumpsuit Ladies S...,8.00,7,EUR,20000,1,4.25,3127,1919.0,580.0,304.0,128.0,196.0,1,0,1,0,"bodycon jumpsuits,nightwear,Shorts,slim,Body S...",black,M,50,Livraison standard,2,0,44,50,NaN,NaN,CN,Rell Mail,rellmail,"88 % avis positifs (16,803 notes)",16803,4.155032,56455b13b15aab129db58cb7,0,NaN,https://www.wish.com/c/5c91a7ae7cfe8e4e64c36d97,https://contestimg.wish.com/api/webimage/5c91a...,5c91a7ae7cfe8e4e64c36d97,summer,2020-08
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,EUR,10000,1,4.08,1367,722.0,293.0,185.0,77.0,90.0,0,0,0,0,"bohemia,Plus Size,dandelionfloralprinted,short...",navyblue,S,50,Livraison standard,2,0,41,50,NaN,NaN,CN,cxuelin99126,cxuelin99126,"90 % avis positifs (5,316 notes)",5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,EUR,100,1,3.07,28,11.0,3.0,1.0,3.0,10.0,0,0,0,0,"Summer,Panties,Elastic,Lace,Casual pants,casua...",lightblue,S,2,Livraison standard,1,0,26,50,1.0,Quantité limitée !,CN,sell best quality goods,sellbestqualitygoods,"(4,435 notes)",4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,EUR,100,0,3.71,59,24.0,15.0,8.0,3.0,9.0,0,0,0,0,"runningshort,Beach Shorts,beachpant,menbeachsh...",white,SIZE S,15,Livraison standard,2,0,11,50,NaN,NaN,CN,shixueying,shixueying,86 % avis positifs (210 notes),210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,2.50,2,0.0,1.0,0.0,0.0,1.0,0,0,0,0,"Summer,fashion women,Fashion,Lace,Dresses,Dres...",white,Size S.,36,Livraison standard,3,0,29,50,NaN,NaN,CN,modai,modai,77 % avis positifs (31 notes),31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,4.07,14,8.0,3.0,1.0,0.0,2.0,0,0,0,0,"Summer,Leggings,slim,Yoga,pants,Slim Fit,Women...",red,S,50,Livraison standard,2,0,41,50,NaN,NaN,CN,AISHOPPINGMALL,aishoppingmall,"90 % avis positifs (7,023 notes)",7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [ ]:
### Ex-3-Task-3

# set merchant id as the index of the sales dataframe and check index
### BEGIN SOLUTION
# Set 'merchant_id' as the index of the sales dataframe
df_sales = df_sales.set_index('merchantid')
# Check the new index
df_sales.index
### END SOLUTION

Index(['5357bcf2bb72c5504882e889', '5708773c3c02161b3f8c7900',
       '5417aada4ad3ab27e954b76c', '570f3a713a698c14278bb51e',
       '53082ea15aefb07dfe1f2a4f', '53f2beb39020ee03566d6e18',
       '5926c5ace8ff5525241b368d', '5860c757b1e41d4d67d183e8',
       '52bd3ddb34067e4620a4c62d', '5a7b23a69bda4e3d375e7b3f',
       ...
       '574d559cb06e205d099d9107', '5db248327c0d0800c24fc084',
       '54365c349719cd57af2b449b', '581c54c4dd99164b808ca531',
       '564d8f2f3a698c01d97fbb81', '567bad8582c35f28103e5813',
       '5b24edf0d1c360301099e9c6', '5d417e7070327a2743021677',
       '5add589edb5f1f32114d07df', '5d4b8931933fb13f8a1fe232'],
      dtype='object', name='merchantid', length=958)

In [ ]:
### Ex-3-Task-4
sorted_df = None
## Sort the sales dataframe by rating in Ascending Order, if two records have same rating then sort in descending order by total unit sold
### BEGIN SOLUTION
sorted_df = df_sales.sort_values(by=['rating', 'totalunitssold'], ascending=[True, False])
### END SOLUTION

In [ ]:
### Ex-3-Task-5
portion_df = None
### Get the sorted dataframe for which rating is 4.041 and store in portion_df
### BEGIN SOLUTION
portion_df = df_sales[df_sales['rating'] == 4.041].sort_values(by='rating', ascending=False)
portion_df
### END SOLUTION

,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
merchantid,,,,,,,,,,,,
5810b1db3deb94160f5cd4a3,1,5000,5000.0,4.041,15436.0,6.0,6.0,0.0,0.0,616.0,NaN,NaN
58380161e18c0f0c70dd6907,1,5000,5000.0,4.041,14194.0,8.0,7.0,-14.0,-14.0,1248.0,NaN,NaN
53e98c6446188e1d4d3a38bd,1,1000,1000.0,4.041,4230.0,1.8,2.0,10.0,10.0,76.0,NaN,NaN
580c7d0a8b67fa197454a2d1,3,300,100.0,4.041,4705.0,6.0,6.0,0.0,0.0,27.0,1.0,33.0
5eba4bab58ed6ba265685ba1,2,200,100.0,4.041,123.0,8.0,10.0,20.0,20.0,58.0,1.0,50.0
5b4973b049c8e64e07c31cb4,1,100,100.0,4.041,267.0,9.0,49.0,82.0,82.0,109.0,NaN,NaN

### Data Types and Conversion

In [ ]:
### Ex-4-Task-1

# the price of the product is upto 2 digit place. I want to convert it into int
### BEGIN SOLUTION
df_product['price'] = df_product['price'].astype(int)
### END SOLUTION

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   int64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(8), int64(16), object(19)
memory usage: 528.6+ KB

In [ ]:
### Ex-4-Task-2
# The datatype of the craw_month is Object type. I want to convert it to data time format and store it in same columns
### BEGIN SOLUTION
df_product['crawl_month'] = pd.to_datetime(df_product['crawl_month'])
### END SOLUTION

## Data Selection and Filtering

### Selecting Columns and Rows

In [ ]:
### Ex-5-Task-1
ser = None

# Select a 'title' column from product dataframe and store in separate variables as series (ser)
### BEGIN SOLUTION
ser = df_product['title']
### END SOLUTION

In [ ]:
### Ex-5-Task-2
product_price = None
# Select multiple columns ('title', 'price', and 'retail price' ) from product dataframe and store in variable product_price.
### BEGIN SOLUTION
product_price = df_product[['title', 'price', 'retail_price']]
### END SOLUTION

### Selection by labels and Selection by position

In [ ]:
### Ex-5-Task-3
single_data = None
## Select a data of title column and at index 1572 of product dataframe
### BEGIN SOLUTION
single_data = df_product.loc[1572, 'title']
single_data
### END SOLUTION

'Pantalon de yoga pour femmes à la mode Slim Fit Fitness Running Leggings'

In [ ]:
### Ex-5-Task-4
single_data = None
## Select a data of 6th column and at  5tj row of product dataframe
### BEGIN SOLUTION
single_data = df_product.iloc[4, 5]
print(single_data)
### END SOLUTION

100

In [ ]:
### Ex-5-Task-5
sliced_data = None
## Select a portion of data frame with column name currency_buyer, units_sold, merchant_rating_count, merchant_rating and with index 100 to 200
### BEGIN SOLUTION
sliced_data = df_product.loc[100:200, ['currency_buyer', 'units_sold', 'merchant_rating_count', 'merchant_rating']]
### END SOLUTION

In [ ]:
### Ex-5-Task-6
sliced_data = None
## Select a portion of data frame with 3rd to 8th columns and with rows 100 to 200
# it must only include 100 rows and 7 columns
### BEGIN SOLUTION
sliced_data = df_product.iloc[100:200, 3:9]
sliced_data
### END SOLUTION

,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count
100,8,EUR,100,1,3.18,72
101,8,EUR,10000,0,3.96,1338
102,17,EUR,100,1,2.80,15
103,5,EUR,5000,0,3.89,1161
104,65,EUR,100,0,3.97,29
...,...,...,...,...,...,...
195,7,EUR,50,0,4.00,6
196,169,EUR,1000,1,3.38,542
197,7,EUR,10000,1,3.70,2441
198,26,EUR,1000,1,3.01,205
199,10,EUR,1000,0,3.67,215

### Boolean Indexing and Conditional Filtering

In [ ]:
### Ex-5-Task-7
mean = None
Q3 = None
records = None
# Find mean and 3rd quantile of the price from product dataframe and get all the records that lies between mean and Q3
### BEGIN SOLUTION
mean = df_product['price'].mean()
Q3 = df_product['price'].quantile(0.75)
records = df_product[(df_product['price'] > mean) & (df_product['price'] <= Q3)]
### END SOLUTION

In [ ]:
### Ex-5-Task-8
summer_product = None
## Find all the row in product dataframe containing 'summer' keyword in its title. Make sure the string is lower to get all the records.
### BEGIN SOLUTION
summer_product = df_product[df_product['title'].str.lower().str.contains('summer')]
### END SOLUTION

## Handling Missing Data

In [ ]:
### Ex-6-Task-1
count_na = None
# Count the number of null data in each columns
### BEGIN SOLUTION
count_na = df_product.isnull().sum()
### END SOLUTION
df_product[['rating_five_count', 'rating_four_count']]

      rating_five_count  rating_four_count
0                  26.0                8.0
1                2269.0             1027.0
2                   5.0                4.0
3                 295.0              119.0
4                   6.0                4.0
...                 ...                ...
1568              722.0              293.0
1569               11.0                3.0
1570               24.0               15.0
1571                0.0                1.0
1572                8.0                3.0

[1573 rows x 2 columns]

In [ ]:
### Ex-6-Task-2

# Impute the  product color with maximum occur value as it is the categorical columns
# Impute the rating five count by mean and rating four count by median of respective columns
### BEGIN SOLUTION
# Imputing product_color with the most frequent value (mode)
df_product['product_color'].fillna(df_product['product_color'].mode()[0], inplace=True)
# Imputing rating_five_count with mean
df_product['rating_five_count'].fillna(df_product['rating_five_count'].mean(), inplace=True)
# Imputing rating_four_count with median
df_product['rating_four_count'].fillna(df_product['rating_four_count'].median(), inplace=True)
### END SOLUTION
# df_product['rating_four_count'].unique()

<ipython-input-114-79da678f18e5>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_product['product_color'].fillna(df_product['product_color'].mode()[0], inplace=True)
<ipython-input-114-79da678f18e5>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_product['rating_five_count'].fillna(df_product['rating_five_count'].mean(), inplace=True)

## Data Cleaning

### Removing Duplicates

In [ ]:
### Ex-7-Task-1
duplicate_count = None
df_drop_duplicate = None # store the data frame after removing duplicates
# Count no. of duplicates value in product dataframe and drop all the duplicate values
### BEGIN SOLUTION
duplicate_count = df_product.duplicated().sum()  # Count duplicates
df_drop_duplicate = df_product.drop_duplicates()  # Drop duplicates
### END SOLUTION

## Data Transformation

### Applying Functions: Apply, map

In [ ]:
### Ex-7-Task-2

df_sales['total_profit'] = None
# Calculate the total profit using apply function in pandas and save in total_profit column
# Formulae: total_profit = (mean product price - mean retail price) * total units sold
### BEGIN SOLUTION
# Step 1: Calculate the required aggregate values
mean_price = df_product['price'].mean()
mean_retail_price = df_product['retail_price'].mean()
total_units_sold = df_product['units_sold'].sum()
# Step 2: Use apply (though apply is not needed, we'll use it as requested)
df_sales['total_profit'] = df_sales.apply(
    lambda row: (mean_price - mean_retail_price) * total_units_sold,
    axis=1
)
### END SOLUTION

### Binning and Categorizing Data

In [ ]:
### Ex-7-Task-3
df_product['sales_category'] = None
# Divide the row into three category based on their units sold and save it into the sales_category column of produdct dataframe
# category are : low_sales, medium sales, and high sales
### BEGIN SOLUTION
# bins = [float('-inf'), 100, 1000, float('inf')]
labels = ['low_sales', 'medium_sales', 'high_sales']
# Apply pd.cut to create the sales_category column
df_product['sales_category'] = pd.cut(df_product['units_sold'], bins=3, labels=labels, right=False)
### END SOLUTION

## Data Aggregation and Grouping

### Groupby aggregation function

In [ ]:
### Ex-8-Task-1
group_df = None
# Create a group of low, medium and high sales and then calulcate, mean of price, median of retail price, min of units_sold and max of rating_five_count of each category
### BEGIN SOLUTION
group_df = df_product.groupby('sales_category').agg({
    'price': 'mean',
    'retail_price': 'median',
    'units_sold': 'min',
    'rating_five_count': 'max'
})
### END SOLUTION

In [ ]:
print(group_df)

                   price  retail_price  units_sold  rating_five_count
sales_category
high_sales      8.366486          10.0        1000       11548.000000
low_sales       8.043165          12.0           1         442.263743
medium_sales    7.929273          10.0         100         442.263743

In [ ]:
### Ex-8-Task-2
group_df = None
## Calculate the Coefficient of Variation of each sales category
### BEGIN SOLUTION
group_df = df_product.groupby('sales_category')['price'].agg(['mean', 'std'])
group_df['coefficient_of_variation'] = (group_df['std'] / group_df['mean']) * 100
### END SOLUTION

In [ ]:
### Ex-8-Task-3
df_product['price_zscore'] = None
## Calculate the Z_score of price for each sales category
### BEGIN SOLUTION
# Define a function to compute z-score within each group
def calculate_zscore(group):
    mean_price = group['price'].mean()
    std_price = group['price'].std()
    group['price_zscore'] = (group['price'] - mean_price) / std_price
    return group
# Apply the function to each group
df_product = df_product.groupby('sales_category').apply(calculate_zscore)
### END SOLUTION

<ipython-input-34-ccc90083b79d>:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_product = df_product.groupby('sales_category').apply(calculate_zscore)

## Merging

In [ ]:
print(df_sales.columns)
print(df_product.columns)

Index(['index', 'merchant_id', 'listedproducts', 'totalunitssold',
       'meanunitssoldperproduct', 'rating', 'merchantratingscount',
       'meanproductprices', 'meanretailprices', 'averagediscount',
       'meandiscount', 'meanproductratingscount', 'totalurgencycount',
       'urgencytextrate', 'total_profit'],
      dtype='object')
Index(['title', 'title_orig', 'price', 'retail_price', 'currency_buyer',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month', 'sales_category', 'performance'],
      dtype='object')

In [ ]:
### Ex-9-Task-1
merged_df = None
# Merge the sales and product dataframe and delete all the non common entries. Merge two dataframe based on merchant id.
### BEGIN SOLUTION
df_sales.reset_index(inplace=True) # Step 1: Reset index to move 'merchantid' back to a column
# df_sales.rename(columns={'merchantid': 'merchant_id'}, inplace=True)  # Step 2: Rename to match column in df_product
merged_df = pd.merge(df_sales, df_product, left_on='merchantid', right_on='merchant_id', how='inner').reset_index(drop=True)  # Step 3: Merge using the common key
### END SOLUTION

ValueError: cannot insert level_0, already exists

# Data Wrangling End to End

## Data Cleaning

#### Features and Columns
The data was scraped in the french localisation (hence some non-ascii latin characters such as « é » and « à ») in the title column.

The title_orig on the other hand contains the original title (the base title) that is displayed by default. When a translation is provided by the seller, it appears in the title column. When the title and title_orig columns are the same, it generally means that the seller did not specify a translation that would be displayed to users with french settings.

A picture is worth a thousand words. In the following screenshot you see some features and how to interpret them.

![](wish_viz.jpg)

In [ ]:
### Ex-10-Task-1
df = None
# Read the product data frame with rating and performance
### BEGIN SOLUTION
df = pd.read_csv('summer-products-with-rating-and-performance_2020-08.csv')
df.info()
### END SOLUTION

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 528.6+ KB

There are total 43 columns. Let's try to reduce the number.

#### Some considerations:
- Excluded product color and size because it's just showing the ones that were found in getting the data : there are more colors and sizes for each product so having just one for each category doesn't say much.
- Excluded currency used, as every price is in EUR
- Excluded shipping option, the "shipping_is_express" column is enough.
- Excluded product's and merchant's id's and pictures, that won't be needed.
- Use only original title

After removal of column, it must only have these columns.

'title_orig', 'price', 'retail_price',
'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
'rating_five_count', 'rating_four_count', 'rating_three_count',
'rating_two_count', 'rating_one_count', 'badges_count',
'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
'tags', 'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
'inventory_total', 'has_urgency_banner',
'merchant_rating_count', 'merchant_rating',
'merchant_has_profile_picture'

In [ ]:
### Ex-10-Task-2
df = df[['title_orig', 'price', 'retail_price',
        'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'shipping_option_price','shipping_is_express', 'countries_shipped_to',
        'has_urgency_banner','merchant_rating_count', 'merchant_rating','merchant_has_profile_picture',
        ]]

# print(df.info())
# print(df.isna().sum())
# print(df['has_urgency_banner'].value_counts())
# Check the data frame information, total no. of null entries in each columns and has_urgency_banner columns counts
# After loading the data we se we have 1573 entries and some null values, let's see what some of them are about:
# - Exactly 45 for rating counts from 1 to 5 star, could it be that there are products with no ratings at all?
# - 1100 null values in the has urgency banner : the values there are 1's so the null values should be turned into 0's
# Now, Rename the columns 'has_urgency_banner' to 'is_running_out' and 'title_orig' to 'title' to make it more clear.
# **Fix the runing out column. fill all the null values with 0's.
### BEGIN SOLUTION
# Check dataframe info
print(df.info())
# Check total number of null entries in each column
print(df.isna().sum())
# Check value counts for 'has_urgency_banner' column
print(df['has_urgency_banner'].value_counts(dropna=False))
# Fill null values in 'has_urgency_banner' with 0
df['has_urgency_banner'] = df['has_urgency_banner'].fillna(0)
# Rename columns for clarity
df = df.rename(columns={'has_urgency_banner': 'is_running_out', 'title_orig': 'title'})
### END SOLUTION

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title_orig                    1573 non-null   object
 1   price                         1573 non-null   float64
 2   retail_price                  1573 non-null   int64
 3   units_sold                    1573 non-null   int64
 4   uses_ad_boosts                1573 non-null   int64
 5   rating                        1573 non-null   float64
 6   rating_count                  1573 non-null   int64
 7   rating_five_count             1528 non-null   float64
 8   rating_four_count             1528 non-null   float64
 9   rating_three_count            1528 non-null   float64
 10  rating_two_count              1528 non-null   float64
 11  rating_one_count              1528 non-null   float64
 12  badges_count                  1573 non-null   int64
 13  badge_local_product           1573 non-null   int64
 14  badge_product_quality         1573 non-null   int64
 15  badge_fast_shipping           1573 non-null   int64
 16  tags                          1573 non-null   object
 17  shipping_option_price         1573 non-null   int64
 18  shipping_is_express           1573 non-null   int64
 19  countries_shipped_to          1573 non-null   int64
 20  has_urgency_banner            473 non-null    float64
 21  merchant_rating_count         1573 non-null   int64
 22  merchant_rating               1573 non-null   float64
 23  merchant_has_profile_picture  1573 non-null   int64
dtypes: float64(9), int64(13), object(2)
memory usage: 295.1+ KB
None
title_orig                         0
price                              0
retail_price                       0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
has_urgency_banner              1100
merchant_rating_count              0
merchant_rating                    0
merchant_has_profile_picture       0
dtype: int64
has_urgency_banner
NaN    1100
1.0     473
Name: count, dtype: int64

#### Check if all the 45 null values for all rating columns belong to same product.
- Get the dataframe for which rating_five_count have null values
- Then, Count the no. of null values for four, three, two and one rating column.

Conclusion: As expected we see the null values in the rating are actually of the same 45 products

In [ ]:
### Ex-10-Task-3
df[df['rating_five_count'].isna()][['rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count']].isna().sum()
df[df['rating_five_count'].isna()].head()
# They seem to be having a rating of 5 even with no ratings: we are going to change the rating and all the rating counts to 0
### BEGIN SOLUTION
# Get the dataframe where rating_five_count is null
null_rating_df = df[df['rating_five_count'].isna()]
# Count null values in other rating columns for these rows
null_counts = null_rating_df[['rating_four_count', 'rating_three_count', 'rating_two_count', 'rating_one_count']].isna().sum()
print(null_counts)
# Show first few rows of these null-rating-five-count products
print(null_rating_df.head())
# Set rating and all rating counts to 0 for these rows
df.loc[df['rating_five_count'].isna(), ['rating', 'rating_count',
                                        'rating_five_count', 'rating_four_count',
                                        'rating_three_count', 'rating_two_count',
                                        'rating_one_count']] = 0
### END SOLUTION

rating_four_count     45
rating_three_count    45
rating_two_count      45
rating_one_count      45
dtype: int64
                                                 title  price  retail_price  \
74   Fashion Women Sleeveless Lace Vest Loose V Nec...   8.00            33
112  Womens Summer Fashion Lip Print 2pc Set Ladies...   5.00            51
126  Women's Casual Sleeveless Stripe T Shirts Dres...   2.72             9
189  Women's Active Skort Athletic Stretchy Pleated...   5.00             5
216  Women's Sexy Push Up Bikini Vintage Set Sexy B...  11.00            30

     units_sold  uses_ad_boosts  rating  rating_count  rating_five_count  \
74           10               0     5.0             0                NaN
112          10               0     5.0             0                NaN
126           1               0     5.0             0                NaN
189          10               0     5.0             0                NaN
216          10               0     5.0             0                NaN

     rating_four_count  rating_three_count  rating_two_count  \
74                 NaN                 NaN               NaN
112                NaN                 NaN               NaN
126                NaN                 NaN               NaN
189                NaN                 NaN               NaN
216                NaN                 NaN               NaN

     rating_one_count  badges_count  badge_local_product  \
74                NaN             0                    0
112               NaN             0                    0
126               NaN             0                    0
189               NaN             0                    0
216               NaN             0                    0

     badge_product_quality  badge_fast_shipping  \
74                       0                    0
112                      0                    0
126                      0                    0
189                      0                    0
216                      0                    0

                                                  tags  shipping_option_price  \
74   Vest,Fashion,Lace,V-neck,Women's Fashion,laceb...                      2
112  Summer,Shorts,Shirt,Sleeve,sportsset,short sle...                      1
126  Summer,Plus Size,Shirt,long dress,Dress,Women'...                      1
189  ladies skort,running skirt,summer skirt,Golf,s...                      2
216  woman fashion,Fashion,outside,Vintage,sexy bik...                      3

     shipping_is_express  countries_shipped_to  is_running_out  \
74                     0                    25             0.0
112                    0                    36             0.0
126                    0                    33             0.0
189                    0                     8             1.0
216                    0                    78             1.0

     merchant_rating_count  merchant_rating  merchant_has_profile_picture
74                    1496         4.169786                             0
112                    295         3.989831                             0
126                    378         3.597884                             0
189                    129         3.837209                             0
216                  22621         4.295124                             0

## Data Exploration

```df['units_sold'].unique()```

It seems like they are all numbers approximated to their lower bound. So let's pretend they are divided in ranges like this:

- 10-100
- 100-1000
- 1000-5000
- 5000-10000
- 10000-20000
- 20000-50000
- 50000-100000
- 100000+

Let's define 3 performance characteristics:

- Average : 0-1000
- Successful: 1000-20000
- Very Successful 20000+

Find the percentage of product belongs to each category.
Steps:
1. First find the performance category and store in performance columns
2. Then, Calculate the percentage of product in each performance category

In [ ]:
df['units_sold'].unique()

array([   100,  20000,   5000,     10,  50000,   1000,  10000, 100000,
           50,      1,      7,      2,      3,      8,      6])

In [ ]:
### Ex-10-Task-4
percentage_of_product_in_each_performance_category = None
### BEGIN SOLUTION
# Define a function to categorize performance based on units_sold
df['performance'] = pd.cut(df['units_sold'], bins=[0, 1000, 20000, float('inf')], labels=['Average', 'Successful', 'Very Successful'])
percentage_of_product_in_each_performance_category = (df['performance'].value_counts()/df['performance'].value_counts().sum()) * 100
### END SOLUTION

performance
Successful         50.794660
Average            41.195168
Very Successful     8.010172
Name: proportion, dtype: float64

## Product Rating and Performance Comparision

Looking at the rating columns I notice two things:

- Some products have a rating count that's too low to be considered, let's only look at products with more than 150 ratings to try to have a fair result
- The rating of the products is a decimal number: let's create another column that categorizes each product into it's rating range.
    - columns are
        1. < 1 if rating < 1
        2. 1-2 if rating >= 1 and rating < 2
        3. 2-3 if rating >= 2 and rating < 3
        4. 3-4 if rating >= 3 and rating < 4
        5. 4-5 if rating >= 4 and rating < 5
- Create pivot table with performance in index, raiting_range in column and no. of product as values

In [ ]:
### Ex-10-Task-5
df_ratings = pd.DataFrame()  ## get records with rating_count > 100
df_ratings['rating_range'] = None
pivot_table = None
### BEGIN SOLUTION
# Filter products with rating_count > 150
df_ratings = df[df['rating_count'] > 150].copy()
# Define function to assign rating ranges
def rating_range(r):
    if r < 1:
        return '<1'
    elif 1 <= r < 2:
        return '1-2'
    elif 2 <= r < 3:
        return '2-3'
    elif 3 <= r < 4:
        return '3-4'
    elif 4 <= r < 5:
        return '4-5'
    else:
        return None
# Apply rating range function
df_ratings['rating_range'] = df_ratings['rating'].apply(rating_range)
# Create pivot table with performance as index, rating_range as columns and count of products as values
pivot_table = pd.pivot_table(df_ratings, index='performance', columns='rating_range',
                             values='title', aggfunc='count', fill_value=0)
pivot_table
### END SOLUTION

rating_range     2-3  3-4  4-5
performance
Average            0    3    0
Successful         4  402  250
Very Successful    2   78   46

This table shows that if the product have average rating of 3-4. THen, it is most likely to be successful product.